* Final Python 3.10 setup

OK, here are the basics and the configure lines that were used for cross compiling Python 3.10 for NAO 5 and NAO 6. The process is as follows.

This is all done using an Ubuntu 22.04 LTS machine with the NAO cross-toolchain installed (both for NAO 5 and NAO 6).

1. Make sure that you have your paths set correctly for the compilers.
   #+begin_example
   # For Nao 5 add path /path/to/ctc-linux64-atom-2.1.4.13/cross/bin
   # For Nao 6 add path /path/to/ctc-linux64-atom-2.8.7.4-20210818_162500/yocto-sdk/sysroots/x86_64-naoqisdk-linux/usr/bin/i686-sbr-linux
   #+end_example

   We will put everything in the path /home/nao/remote_control as that is where it will live on the NAO. These instructions assume you are only building for one type of robot. If you are building for both, adjust the patch accordingly (e.g., /home/nao/remote_control.nao5 as the path instead).

2. Build OpenSSL 3.0 (not strictly necessary for NAO 6, but an OK precaution). We used OpenSSL 3.0.8

#+begin_example
   # For Nao 5
   mkdir nao5-openssl-build
   cd !$
   /path/to/openssl3/Configure linux-x86 --prefix=/home/nao/remote_control/openssl3 --cross-compile-prefix=i686-aldebaran-linux-gnu-
   make
   make install


   # For Nao 6
   /path/to/openssl3/Configure linux-x86 --prefix=/home/nao/remote_control/openssl3 --cross-compile-prefix=i686-sbr-linux-
   make
   make install
#+end_example

3. Build Python 3.10 for the host system (we used Python 3.10.10). It is encouraged to build a straight Python because one doesn't know if a distro has additional patches that may cause problems. You only need to do this once, you can enable optimizations if you want. Since it is only used for building, it's not as important.

#+begin_example
   # Make sure that libffi-dev (or some variant) is installed
   mkdir python-host
   ./configure --prefix /some/path
   make
   make install
   # Add this /some/path/bin to your PATH
#+end_example   


4. Build Python 3.10 for NAO, you will probably also want to ensure that the zip module is also built. Here are the steps:

   #+begin_example
   # For NAO 5
   mkdir build-nao5
   cd !$
   ../path/to/Python-3.10.10/configure '--prefix=/home/nao/remote_control/python3.10' '--build=x86_64-pc-linux-gnu' '--host=i686-aldebaran-linux-gnu' 'ac_cv_buggy_getaddrinfo=no' 'ac_cv_file__dev_ptmx=yes' 'ac_cv_file__dev_ptc=no' '--enable-optimizations' '--with-openssl=/home/nao/remote_control/openssl3' '--with-system-ffi' 'build_alias=x86_64-pc-linux-gnu' 'host_alias=i686-aldebaran-linux-gnu' 'CFLAGS=-I/netopt/nao-sdks/ctc-linux64-atom-2.1.4.13/ffi/lib/libffi-3.0.10/include -I/netopt/nao-sdks/ctc-linux64-atom-2.1.4.13/zlib/include' 'CPPFLAGS=-I/netopt/nao-sdks/ctc-linux64-atom-2.1.4.13/ffi/lib/libffi-3.0.10/include'
   make
   make install

   # For NAO 6
   mkdir build-nao6
   ../path/to/Python-3.10.10/configure '--prefix=/home/nao/remote_control/python3.10' '--build=x86_64-pc-linux-gnu' '--host=i686-sbr-linux' 'ac_cv_buggy_getaddrinfo=no' 'ac_cv_file__dev_ptmx=yes' 'ac_cv_file__dev_ptc=no' '--enable-optimizations' '--with-openssl=/home/nao/remote_control/openssl3' 'build_alias=x86_64-pc-linux-gnu' 'host_alias=i686-sbr-linux' 'CC=i686-sbr-linux-gcc --sysroot /netopt/nao-sdks/ctc-linux64-atom-2.8.7.4-20210818_162500/yocto-sdk/sysroots/core2-32-sbr-linux -Wl,--as-needed,--sysroot /netopt/nao-sdks/ctc-linux64-atom-2.8.7.4-20210818_162500/yocto-sdk/sysroots/core2-32-sbr-linux' 'CFLAGS=-pipe -fomit-frame-pointer  -m32 -march=core2 -mtune=core2  -mssse3 -mfpmath=sse -O2 -I/netopt/nao-sdks/ctc-linux64-atom-2.8.7.4-20210818_162500/yocto-sdk/sysroots/core2-32-sbr-linux/usr/lib/libffi-3.2.1/include' '--with-system-ffi'
   make
   make install
#+end_example

This should give you a Python 3.10 that supports most of what you need.    


* Cross-compiling ZMQ 

The toolchain configuration defined for cmake in the Nao5 compilers is wrong (don't need to use FORCE, just use regular).

You can't just take pyzmq from Nao6 and have it work on Nao5. They are  different architectures and there's a problem with conversion to unicode mismatch.

You can follow the instructions [[https://crossenv.readthedocs.io/en/latest/quickstart.html#build-or-obtain-host-python][Crossenv]] to set up a cross-python environment. The configure line for host python is.

** Zmq for NAO 5

Yes, you can build the thing zeromq more or less the same as before. Just make sure you have the toolchain configured.

#+begin_example
cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=~/.local/share/qi/toolchains/nao5toolchain/toolchain-nao5toolchain.cmake -DCMAKE_INSTALL_PREFIX=/home/nao/remote_control/zmq -DCMAKE_BUILD_TYPE=Release ../

#+end_example

Unfortunately, there are problems with the binaries, as it needs to link to clock_gettime, it seems to be enough.  The CMakefile had to be edited to add it to the link line for zmq and turn off building tests.

You must also build PyZMQ for Python 2 and Python 3. I had to follow my previous version, but also hardcode the zmq version because I couldn't run vers. This seems to be a problem with crossenv, but setting CFLAGS and CXXFLAGS  explicitly helps:

*** For Python 2

#+begin_example
export PATH=/netopt/nao-sdks/ctc-linux64-atom-2.1.4.13/cross/bin:$PATH
CFLAGS="-pipe -fomit-frame-pointer -fno-align-jumps -fno-align-functions -fno-align-labels -fno-align-loops -m32 -mtune=atom -mssse3 -mfpmath=sse --sysroot /netopt/nao-sdks/ctc-linux64-atom-2.1.4.13/cross/i686-aldebaran-linux-gnu/sysroot -isystem /netopt/nao-sdks/ctc-linux64-atom-2.1.4.13/cross/include -I/netopt/nao-sdks/ctc-linux64-atom-2.1.4.13/python/include/python2.7"
export CXXFLAGS="$CFLAGS -std=c++0x"

export CC=i686-aldebaran-linux-gnu-gcc
export LDSHARED="$CC -shared"
pip download "pyzmq==19.0.2" 
tar zxvf pyzmq-19.0.2.tar.gz
cd pyzmq-19.0.2
# Python here is python2 on host…
python setup.py configure --plat-name=i686-aldebaran-linux-gnu --zmq=/home/nao/remote_control/zmq

# Fix setup so that it uses the correct version.

python setup.py build
setup.py install --prefix=/home/nao/remote_control/py2-pyzmq

#+end_example

*** For Python 3

For Python 3, we can use Crossenv.  It still has some rough edges as can be seen by the pyzmq above.

It seems you can also bundle up the cross directory and splat it out on the robot. That is cool.


Now setup crossenv and build a crossenv for it

pyzmq doesn't work so, easy, so we need to massage it a little, but it works very similar to building for Python 2 on Nao 5.

#+begin_example
cd python310_cross
export PATH=/netopt/nao-sdks/ctc-linux64-atom-2.1.4.13/cross/bin:$PATH
CFLAGS="-pipe -fomit-frame-pointer -fno-align-jumps -fno-align-functions -fno-align-labels -fno-align-loops -m32 -mtune=atom -mssse3 -mfpmath=sse --sysroot /netopt/nao-sdks/ctc-linux64-atom-2.1.4.13/cross/i686-aldebaran-linux-gnu/sysroot -isystem /netopt/nao-sdks/ctc-linux64-atom-2.1.4.13/cross/include -I/netopt/nao-sdks/ctc-linux64-atom-2.1.4.13/python/include/python2.7"
export CXXFLAGS="$CFLAGS -std=c++0x"

export CC=i686-aldebaran-linux-gnu-gcc
export LDSHARED="$CC -shared"
pip download "pyzmq==19.0.2" 
tar zxvf pyzmq-19.0.2.tar.gz
cd pyzmq-19.0.2
patch -p0 < pyzmq-19.0.2-build.diff
python3 setup.py configure --plat-name=i686-aldebaran-linux-gnu --zmq=/home/nao/remote_control/zmq
python3 setup.py build
python3 setup.py install --prefix=/home/nao/remote_control/python310_cross/cross
#+end_example

Now we should have a copy of all the packages we need in /home/nao/remote_control/python310_cross/cross/lib directory, we'll move those into the cross-compiled python.

#+begin_example
cp -R /home/nao/remote_control/python310_cross/cross/lib/python3.10/site-packages/* /home/nao/remote_control/python3.10/lib/python3.10/site-packages
# You can now remove the cross environment.
#+end_example


You can tar it up and copy it over to NAO.
#+begin_example
tar cvfz nao5-python310.tar.gz remote_control
scp nao5-python310.tar.gz naoX:
#+end_example

While we are on the main machine, let's sync the remote over as well.

* For NAO 6

The process is more or less the same for NAO 6, with paths changed to the correct cross-tools and changing the CMAKE_TOOLCHAIN_FILE. Here is how you configure pyzmq for a NAO 6.

#+begin_example
python3 setup.py configure --plat-name=i686-sbr-linux --zmq=/home/nao/remote_control/zmq
python3 setup.py build
python3 setup.py install --prefix=/home/nao/remote_control/python310_cross/cross
#+end_example


